AWSTemplateFormatVersion: '2010-09-09'
Description: Common resources for ScoutSuite Batch
# Stack Name : scoutsuite-common
# Description : this stack creates the ScoutSuite main stack prerequisites :
# - one ECR repository
# - if needed, one S3 bucket to store reports (otherwise use an external one)


Parameters:

  TagBlock:
    Description: Block tag
    Type: String
    Default: security

  TagApp:
    Description: Application tag
    Type: String
    Default: scoutsuite

  TagOrg:
    Description: Organization Unit
    Type: String
    Default: cloudteam

  ScoutSuiteEcrRepoName:
    Description: ECR name for the ScoutSuite repo
    Type: String
    Default: prowler

  UseOwnReportingBucket:
    Description: Enable a dedicated Bucket to store reports
    Type: String
    Default: true
    AllowedValues: [true, false]

Conditions:
  HasOwnReportingBucket: !Equals [!Ref UseOwnReportingBucket, true]


Resources:

  ScoutSuiteEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${ScoutSuiteEcrRepoName}'

  ScoutSuiteS3Bucket:
    Type: AWS::S3::Bucket
    Condition: HasOwnReportingBucket
    Properties:
      BucketName: !Sub '${TagApp}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      Tags:
      - Key: Block
        Value: !Sub '${TagBlock}'
      - Key: App
        Value: !Sub '${TagApp}'
      - Key: Org
        Value: !Sub '${TagOrg}'

Outputs:

  ScoutSuiteEcrRepository:
    Description: ScoutSuite ECR repository
    Value: !GetAtt ScoutSuiteEcrRepository.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EcrRepository"
