---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack providing cross account access for ScoutSuite
# Suggested StackName : scoutsuite-spoke-account

Parameters:

  ScoutSuiteCentralAccount:
    Description: AWS account ID where ScoutSuite is installed
    Type: String
    ConstraintDescription: Must be a valid AWS account ID

  ScoutSuiteRoleExternalId:
    Description: CloudSploit Role ExternalID
    Type: String

Resources:

  ScoutSuiteScanAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: scoutsuite-scan-role
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${ScoutSuiteCentralAccount}:root'
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              "sts:ExternalId": !Sub '${ScoutSuiteRoleExternalId}'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      Path: "/"
