---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack providing cross account access for ScoutSuite

Parameters:

  ScoutSuiteCentralAccount:
    Description: ScoutSuite AWS accountId
    Type: String
    ConstraintDescription: Must be a valid AWS account ID

  ScoutSuiteRoleExternalId:
    Description: ScoutSuite Role ExternalID
    Type: String

  ScoutSuiteStackSetSpokeName:
    Description: Name of the StackSet in charge of distributing spoke account assets
    Type: String
    Default: scoutsuite-spoke-account

Resources:

  ScoutSuiteOrgRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: scoutsuite-organizations-role
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${ScoutSuiteCentralAccount}:root'
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              "sts:ExternalId": !Sub '${ScoutSuiteRoleExternalId}'
      Policies:
      - PolicyName: "AllowOrganizationListAccounts"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: organizations:ListAccounts
            Resource: '*'
      - PolicyName: "AllowUpdateStackInstances"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - cloudformation:CreateStackInstances
            - cloudformation:ListStackInstances
            Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stackset/${ScoutSuiteStackSetSpokeName}:*"
